[build]
  command = "npm run build" # atau "vite build"
  publish = "dist"          # atau "build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev" # atau "vite"
  port = 8888
  publish = "dist"        # atau "build"